### ISSUE TITLE
Process conflict casused abnormal termination

### ISSUE THREAD

**Issue by guanjiayi** [PKU-MARL/Safe-Policy-Optimization#1]
1. Follow the installation instructions to install
2. An exception occurred while executing this command:
` python safepo/train.py --env_id Safexp-PointGoal1-v0 --algo ppo_lagrangian --cores 4`
3.  Exception prompt:

> 
> Traceback (most recent call last):
>   File "safepo/train.py", line 61, in <module>
>     model = Runner(
>   File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/runner.py", line 36, in __init__
>     self.default_kwargs = get_defaults_kwargs_yaml(algo=algo,env_id=env_id)
>   File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/utils.py", line 15, in get_defaults_kwargs_yaml
>     return kwargs[kwargs_name]
> KeyError: 'defaults'

> Primary job  terminated normally, but 1 process returned
> a non-zero exit code.. Per user-direction, the job has been aborted.

> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[52236,1],0]
>   Exit code:    1

**Comment by zmsn-1998** [comment]
This is our negligence. The original meaning of our design is to provide a default parameter setting, and then users can customize their own parameters during use. For more details you can see ppo.yaml in the same directory. You can customize different configurations for different environments.
We already update ppo_lagrangian.yaml, sorry for your bad experience.

Thanks for your feedback.Do you have any other usage questions? QAQ

**Comment by guanjiayi** [comment]
Thank you for your replay, the previous problem has been solved, and other problems appear after starting the model training.

INFO: Sync actor critic parameters
Done! (took 0.564 sec.)
Save model to disk...
Done.
Start with training.
Traceback (most recent call last):
  File "safepo/train.py", line 70, in <module>
    model.train()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/runner.py", line 201, in train
    self.model, self.env = algo.learn()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 285, in learn
    self.update()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 80, in update
    self.update_policy_net(data=data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 466, in update_policy_net
    pi_l_old, pi_info_old = self.compute_loss_pi(data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 60, in compute_loss_pi
    penalty = self.lambda_range_projection(self.lagrangian_multiplier).item()
  File "/home/jiayiguan/anaconda3/envs/safe_policy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ReLU' object has no attribute 'item'
Traceback (most recent call last):
  File "safepo/train.py", line 70, in <module>
    model.train()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/runner.py", line 201, in train
    self.model, self.env = algo.learn()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 285, in learn
    self.update()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 80, in update
    self.update_policy_net(data=data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 466, in update_policy_net
    pi_l_old, pi_info_old = self.compute_loss_pi(data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 60, in compute_loss_pi
    penalty = self.lambda_range_projection(self.lagrangian_multiplier).item()
  File "/home/jiayiguan/anaconda3/envs/safe_policy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ReLU' object has no attribute 'item'
Traceback (most recent call last):
  File "safepo/train.py", line 70, in <module>
    model.train()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/runner.py", line 201, in train
    self.model, self.env = algo.learn()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 285, in learn
    self.update()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 80, in update
    self.update_policy_net(data=data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 466, in update_policy_net
    pi_l_old, pi_info_old = self.compute_loss_pi(data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 60, in compute_loss_pi
    penalty = self.lambda_range_projection(self.lagrangian_multiplier).item()
  File "/home/jiayiguan/anaconda3/envs/safe_policy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ReLU' object has no attribute 'item'
Traceback (most recent call last):
  File "safepo/train.py", line 70, in <module>
    model.train()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/common/runner.py", line 201, in train
    self.model, self.env = algo.learn()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 285, in learn
    self.update()
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 80, in update
    self.update_policy_net(data=data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/policy_graident.py", line 466, in update_policy_net
    pi_l_old, pi_info_old = self.compute_loss_pi(data)
  File "/home/jiayiguan/opt/paper_carla/Safe-Policy-Optimization/safepo/algos/ppo_lagrangian.py", line 60, in compute_loss_pi
    penalty = self.lambda_range_projection(self.lagrangian_multiplier).item()
  File "/home/jiayiguan/anaconda3/envs/safe_policy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ReLU' object has no attribute 'item'

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63484,1],1]
  Exit code:    1

**Comment by zmsn-1998** [comment]
Thank you for your feedback, we fix this bug by update lagrangian_base.py . If you have any other questions, you can let us know and we'll get back to you as soon as possible.

**Comment by guanjiayi** [comment]
thank you for your patience with this issue，the problem has been solved. Thank you very much.
